[project]
name = "athena"
version = "0.2.0"
description = "Adaptive Technology for Human Enhancement, Navigation & Assistance"
readme = "README.md"
requires-python = ">=3.12"

authors = [
    { name = "Amey Kumar" }
]

dependencies = []

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]